package com.SST.server_state_telemetry_client.data.remote

import com.SST.server_state_telemetry_client.domain.model.DiskSummary
import com.SST.server_state_telemetry_client.domain.model.FdInfo
import com.SST.server_state_telemetry_client.domain.model.NetInfo
import com.SST.server_state_telemetry_client.presentation.ui.components.telemetry.formatBytesPerSec
import com.SST.server_state_telemetry_client.presentation.ui.components.telemetry.formatUptime
import java.util.Locale
import org.junit.Assert.*
import org.junit.Test

class SystemStatsDecoderTest {
    // Generated by SSTD PacketUtil::createPacket and packed Protocol.hpp at
    // 08f917cf853785cf026c6c32f7af244097ba3a15. Only header timestamp bytes 12..19
    // are normalized to zero. This is an independent C++-generated wire fixture.
    private val packet = (
        "445453530111000040302010000000000000000086000000ffff5aa52564" +
        "0807060504030201040302f101000080ffffffff0000100000000000103254760700000009000000" +
        "ffffffff0000008012f00180cd5f0100ffffffff01000080" +
        "0807060504030201000400000000000000080000000000000002000000000000" +
        "0010000000000000000400000000000000200000000000000008000000000000"
    ).chunked(2).map { it.toInt(16).toByte() }.toByteArray()

    @Test
    fun decodesLittleEndianSstdPacketWithExactFieldWidths() {
        assertEquals(158, packet.size)
        val stats = requireNotNull(decodeSystemStats(packet))
        assertEquals(0xFFFF, stats.validMask)
        assertEquals(37, stats.cpuUsage)
        assertEquals(100, stats.memUsage)
        assertEquals(NetInfo(0x0102030405060708L, 0xF1020304L, 0x80000001L, 0xFFFFFFFFL), stats.netRx)
        assertEquals(NetInfo(1_048_576L, 0x76543210L, 7L, 9L), stats.netTx)
        assertEquals(0xFFFFFFFFL, stats.procCount)
        assertEquals(0x80000000L, stats.totalProcCount)
        assertEquals(0xF012, stats.netUserCount)
        assertEquals(0x8001, stats.connectedUserCount)
        assertEquals(90_061L, stats.uptimeSecs)
        assertEquals(FdInfo(0xFFFFFFFFL, 0x80000001L), stats.fdInfo)
        assertEquals(
            DiskSummary(0x0102030405060708L, 1_024L, 2_048L, 512L, 4_096L, 1_024L, 8_192L, 2_048L),
            stats.disk
        )
    }

    @Test
    fun rejectsTruncatedHeaderAndBodyWithoutPartialStats() {
        for (size in listOf(0, 1, 23, 24, 25, 157)) {
            assertNull("truncated size=$size", decodeSystemStats(packet.copyOf(size)))
        }
    }

    @Test
    fun rejectsOtherMagicMessageTypesAndBodySizes() {
        assertNull(decodeSystemStats(packet.copyOf().apply { this[0] = 0 }))
        assertNull(decodeSystemStats(packet.copyOf().apply { this[5] = 0x01 }))
        assertNull(decodeSystemStats(packet.copyOf().apply { this[5] = 0xFF.toByte() }))
        assertNull(decodeSystemStats(packet.copyOf().apply { this[20] = 133.toByte() }))
        assertNull(decodeSystemStats(packet.copyOf().apply { this[20] = 135.toByte() }))
    }

    @Test
    fun rejectsBigEndianMagicAndBodyLength() {
        assertNull(decodeSystemStats(packet.copyOf().apply {
            this[0] = 0x53; this[1] = 0x53; this[2] = 0x54; this[3] = 0x44
        }))
        assertNull(decodeSystemStats(packet.copyOf().apply {
            this[20] = 0; this[23] = 134.toByte()
        }))
    }

    @Test
    fun preservesValidityMaskWithoutInventingPerFieldFlags() {
        val stats = requireNotNull(decodeSystemStats(packet.copyOf().apply {
            this[24] = 0x5A; this[25] = 0x80.toByte()
        }))
        assertEquals(0x805A, stats.validMask)
        assertEquals(37, stats.cpuUsage)
        assertEquals(1_048_576L, stats.netTx.bytePerSec)
    }

    @Test
    fun preservesExistingVersionAndTrailingByteAcceptance() {
        val extended = packet.copyOf(packet.size + 4).apply { this[4] = 2 }
        assertEquals(decodeSystemStats(packet), decodeSystemStats(extended))
    }

    @Test
    fun decodedRatesAndUptimeReachDisplayInOriginalUnits() {
        val previous = Locale.getDefault()
        try {
            Locale.setDefault(Locale.US)
            val stats = requireNotNull(decodeSystemStats(packet))
            assertEquals("1.00 MB/s", formatBytesPerSec(stats.netTx.bytePerSec))
            assertEquals("1d 01:01:01", formatUptime(stats.uptimeSecs))
        } finally {
            Locale.setDefault(previous)
        }
    }
}
